---
- name: Set up kubernetes repository
  yum_repository:
    name: kubernetes
    description: kubernetes repo
    baseurl: "{{ kuber_repo }}"
    gpgcheck: yes
    gpgkey: "{{ kuber_gpgkey }}"

- name: Install kubelet, kubeamd, kubectl
  yum:
    name: 
      - kubelet
      - kubeadm
      - kubectl